<a href="https://colab.research.google.com/github/Srikhanth14/Data_Analysis_Projects/blob/main/HealthCare_Resource_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import the Necessary Libraries**

In [1]:
import pandas as pd
import numpy as np

# **Data Collection and Processing**

In [2]:
#Loading the Datasets
data = pd.read_csv("modified_healthcare_dataset.csv")

In [3]:
# Display first three rows of the dataset
data.head(3)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby Jackson,19,Female,AB+,Infections,2024-01-31,Matthew Smith,Northwestern Memorial Hospital,Blue Cross,2212.272701,328,Emergency,2024-02-07,Azithromycin,Normal,7
1,Leslie Terry,15,Female,B-,Flu,2019-08-20,Samantha Davies,UI Health (University of Illinois Hospital),UnitedHealthcare,3185.161388,265,Emergency,2019-08-22,Tamiflu,Abnormal,2
2,Danny Smith,50,Female,A+,Cancer,2022-09-22,Tiffany Mitchell,UI Health (University of Illinois Hospital),Blue Cross,72055.214065,205,Elective,2022-10-30,Cisplatin,Inconclusive,38

In [4]:
# Display last four rows of the dataset
data.tail(4)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
55496,Kyle Perez,63,Male,A+,Heart Disease,2020-01-23,Taylor Sullivan,UI Health (University of Illinois Hospital),Medicare,26828.223456,316,Emergency,2020-03-07,Statins,Abnormal,44
55497,Heather Wang,28,Female,O+,Asthma,2020-07-13,Joe Jacobs DVM,Northwestern Memorial Hospital,Cigna,6041.030866,347,Elective,2020-07-16,Montelukast,Normal,3
55498,Jennifer Jones,75,Male,O+,Cancer,2019-05-25,Kimberly Curry,UChicago Medicine,Aetna,44495.656362,321,Emergency,2019-07-11,Methotrexate,Abnormal,47
55499,James Garcia,53,Female,O+,Diabetes,2024-04-02,Dennis Warren,Loyola University Medical Center,Cigna,15953.455966,448,Emergency,2024-04-12,Insulin,Abnormal,10

In [5]:
#Display the Sample of any 2 rows from the dataset
data.sample(2)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
2750,Meghan Adams,47,Female,A+,Flu,2019-05-15,Daniel Reed,Northwestern Memorial Hospital,Cigna,1257.264846,458,Urgent,2019-05-17,Zanamivir,Normal,2
7191,Cynthia Smith Md,30,Male,AB-,Flu,2023-04-07,Laura Kerr,UChicago Medicine,Cigna,724.668614,195,Emergency,2023-04-10,Oseltamivir,Abnormal,3

In [6]:
#Print the Dimensions of the dataset
print("Number of Rows: ", data.shape[0])
print("Number of Columns: ", data.shape[1])

Number of Rows:  55500
Number of Columns:  16

In [7]:
#Displaying all column names in the Dataset
for col in data.columns:
  print(col)

Name
Age
Gender
Blood Type
Medical Condition
Date of Admission
Doctor
Hospital
Insurance Provider
Billing Amount
Room Number
Admission Type
Discharge Date
Medication
Test Results
Length of Stay

In [8]:
#Checking the Data type of Columns in the Dataset
data.dtypes.to_frame(name="Data_Type")

                   Data_Type
Name                  object
Age                    int64
Gender                object
Blood Type            object
Medical Condition     object
Date of Admission     object
Doctor                object
Hospital              object
Insurance Provider    object
Billing Amount       float64
Room Number            int64
Admission Type        object
Discharge Date        object
Medication            object
Test Results          object
Length of Stay         int64

In [9]:
# Checking any null values present in the each column
if data.isnull().sum().sum() == 0:
  print("No null values present in the dataset")
else:
  print("Null values present in the dataset")

No null values present in the dataset

In [10]:
print(data.isnull().sum())

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
Length of Stay        0
dtype: int64

In [11]:
#Checking any duplicate values present in the Dataset
if data.duplicated().sum() == 0:
  print("Duplicate values doesn't exist in the dataset")
else:
  print("Duplicate values exist in the dataset")

Duplicate values doesn't exist in the dataset

In [12]:
#Statistical Summary of the Dataset
data.describe()

                Age  Billing Amount   Room Number  Length of Stay
count  55500.000000    55500.000000  55500.000000    55500.000000
mean      48.001622    21835.044635    301.134829       17.841009
std       21.105827    23574.413594    115.243069       20.272294
min        5.000000      500.220989    101.000000        1.000000
25%       32.000000     4195.525741    202.000000        4.000000
50%       50.000000    11089.537763    302.000000        8.000000
75%       65.000000    35887.703406    401.000000       28.000000
max       90.000000    99997.797977    500.000000       89.000000

In [13]:
#Overview of the Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
 15  Length of Stay      55500 non-null  int64
dtypes: float64(1), int64(3), object(12)
memory usage: 6.8+ MB

In [14]:
#Identifying the Total unique values in Each Column
data.nunique()

Name                  40235
Age                      86
Gender                    2
Blood Type                8
Medical Condition         8
Date of Admission      1827
Doctor                40341
Hospital                  4
Insurance Provider        5
Billing Amount        55500
Room Number             400
Admission Type            4
Discharge Date         1901
Medication               23
Test Results              3
Length of Stay           89
dtype: int64

In [15]:
print("Frequency of Each Categorical Variables",'\n')
Categorical_Target_Columns = ["Gender","Blood Type", "Medical Condition", "Doctor", "Hospital", "Insurance Provider", "Admission Type", "Medication", "Test Results"]

for categorical_columns in Categorical_Target_Columns:
    print(data[categorical_columns].value_counts())
    print("-"*50)

Frequency of Each Categorical Variables

Gender
Female    27955
Male      27545
Name: count, dtype: int64
--------------------------------------------------
Blood Type
O+     15696
A+     15573
B+      5457
AB-     4485
B-      4408
O-      3341
A-      3301
AB+     3239
Name: count, dtype: int64
--------------------------------------------------
Medical Condition
Flu              7046
Diabetes         7005
Obesity          6994
Cancer           6940
Asthma           6908
Heart Disease    6900
Alzheimer’s      6861
Infections       6846
Name: count, dtype: int64
--------------------------------------------------
Doctor
Michael Smith      27
John Smith         22
Robert Smith       22
Michael Johnson    20
James Smith        20
                   ..
Keith Ortiz         1
Timothy Chapman     1
Terri Collins       1
Jill Jacobson       1
Scott Coleman       1
Name: count, Length: 40341, dtype: int64
--------------------------------------------------
Hospital
Northwestern Memorial Hospital                 14070
UI Health (University of Illinois Hospital)    13950
UChicago Medicine                              13870
Loyola University Medical Center               13610
Name: count, dtype: int64
--------------------------------------------------
Insurance Provider
Cigna               11183
UnitedHealthcare    11142
Blue Cross          11134
Medicare            11038
Aetna               11003
Name: count, dtype: int64
--------------------------------------------------
Admission Type
Emergency    20104
Elective     13280
Urgent       11816
Routine      10300
Name: count, dtype: int64
--------------------------------------------------
Medication
Metformin        4653
Zanamivir        2391
Methotrexate     2375
Glipizide        2362
Orlistat         2351
Insulin          2340
Aspirin          2337
Prednisone       2333
Oseltamivir      2329
Tamiflu          2326
Montelukast      2313
Memantine        2312
Azithromycin     2312
Amoxicillin      2311
Beta-blockers    2297
Doxorubicin      2296
Phentermine      2293
Donepezil        2292
Cisplatin        2269
Statins          2266
Albuterol        2262
Rivastigmine     2257
Ciprofloxacin    2223
Name: count, dtype: int64
--------------------------------------------------
Test Results
Abnormal        27784
Normal          17453
Inconclusive    10263
Name: count, dtype: int64
--------------------------------------------------

In [16]:
print("Distribution of Categorical Variables in Percentage",'\n')
for categorical_columns in Categorical_Target_Columns:
    print(data[categorical_columns].value_counts(normalize=True)*100)
    print("-"*50)

Distribution of Categorical Variables in Percentage

Gender
Female    50.369369
Male      49.630631
Name: proportion, dtype: float64
--------------------------------------------------
Blood Type
O+     28.281081
A+     28.059459
B+      9.832432
AB-     8.081081
B-      7.942342
O-      6.019820
A-      5.947748
AB+     5.836036
Name: proportion, dtype: float64
--------------------------------------------------
Medical Condition
Flu              12.695495
Diabetes         12.621622
Obesity          12.601802
Cancer           12.504505
Asthma           12.446847
Heart Disease    12.432432
Alzheimer’s      12.362162
Infections       12.335135
Name: proportion, dtype: float64
--------------------------------------------------
Doctor
Michael Smith      0.048649
John Smith         0.039640
Robert Smith       0.039640
Michael Johnson    0.036036
James Smith        0.036036
                     ...
Keith Ortiz        0.001802
Timothy Chapman    0.001802
Terri Collins      0.001802
Jill Jacobson      0.001802
Scott Coleman      0.001802
Name: proportion, Length: 40341, dtype: float64
--------------------------------------------------
Hospital
Northwestern Memorial Hospital                 25.351351
UI Health (University of Illinois Hospital)    25.135135
UChicago Medicine                              24.990991
Loyola University Medical Center               24.522523
Name: proportion, dtype: float64
--------------------------------------------------
Insurance Provider
Cigna               20.149550
UnitedHealthcare    20.075676
Blue Cross          20.061261
Medicare            19.888288
Aetna               19.825225
Name: proportion, dtype: float64
--------------------------------------------------
Admission Type
Emergency    36.223423
Elective     23.927928
Urgent       21.290090
Routine      18.558559
Name: proportion, dtype: float64
--------------------------------------------------
Medication
Metformin        8.383784
Zanamivir        4.308108
Methotrexate     4.279279
Glipizide        4.255856
Orlistat         4.236036
Insulin          4.216216
Aspirin          4.210811
Prednisone       4.203604
Oseltamivir      4.196396
Tamiflu          4.190991
Montelukast      4.167568
Memantine        4.165766
Azithromycin     4.165766
Amoxicillin      4.163964
Beta-blockers    4.138739
Doxorubicin      4.136937
Phentermine      4.131532
Donepezil        4.129730
Cisplatin        4.088288
Statins          4.082883
Albuterol        4.075676
Rivastigmine     4.066667
Ciprofloxacin    4.005405
Name: proportion, dtype: float64
--------------------------------------------------
Test Results
Abnormal        50.061261
Normal          31.446847
Inconclusive    18.491892
Name: proportion, dtype: float64
--------------------------------------------------

# **Data Cleaning and Pre-Processing**

In [17]:
#Converting Date Columns to Date Type
data["Date of Admission"] = pd.to_datetime(data["Date of Admission"])
data["Discharge Date"] = pd.to_datetime(data["Discharge Date"])

In [18]:
print(data[["Date of Admission","Discharge Date"]].dtypes)

Date of Admission    datetime64[ns]
Discharge Date       datetime64[ns]
dtype: object

In [19]:
data[["Date of Admission","Discharge Date"]].sample(2)

      Date of Admission Discharge Date
10961        2019-08-04     2019-08-09
3603         2024-04-23     2024-04-26

In [20]:
#Admission and Discharge Date Validation
Date_Validation = data['Discharge Date'] > data['Date of Admission']
print("Are all discharge date valid: ", Date_Validation.all())
print("Total Invalid rows in Date_Validation: ",(~Date_Validation).sum())

Are all discharge date valid:  True
Total Invalid rows in Date_Validation:  0

In [21]:
#Length of Stay Validation
Calculated_Length_Of_Stay = (data['Discharge Date'] - data['Date of Admission']).dt.days
Length_Of_Stay_Validation = data['Length of Stay']== Calculated_Length_Of_Stay
print("Does Length of Stay match the Calculated Length_Of_Stay numbers: ", Length_Of_Stay_Validation.all())
print("Total Invalid rows in Length_of_Stay_Validation: ",(~Length_Of_Stay_Validation).sum())

Does Length of Stay match the Calculated Length_Of_Stay numbers:  True
Total Invalid rows in Length_of_Stay_Validation:  0

In [22]:
#Billing Amount Validation
Billing_Validation = data['Billing Amount']>0
print("Does Billing Amount is greater than zero: ", Billing_Validation.all())
print("Total Invalid rows in Billing Amount: ",(~Billing_Validation).sum())

Does Billing Amount is greater than zero:  True
Total Invalid rows in Billing Amount:  0

In [23]:
#Age Validation
Age_Validation = data['Age'].between(0,100)
print("Are all ages within the valid ranges: ", Age_Validation.all())
print("Total Invalid Values in Ages: ",(~Age_Validation).sum())

Are all ages within the valid ranges:  True
Total Invalid Values in Ages:  0

In [24]:
#Cross checking the consistency of Categorical Target Columns
Categorical_Target_Columns = ["Gender","Blood Type", "Medical Condition", "Hospital", "Insurance Provider", "Admission Type"]

for categorical_columns in Categorical_Target_Columns:
    print(categorical_columns)
    print(data[categorical_columns].unique())
    print("-"*50)

Gender
['Female' 'Male']
--------------------------------------------------
Blood Type
['AB+' 'B-' 'A+' 'O+' 'O-' 'AB-' 'A-' 'B+']
--------------------------------------------------
Medical Condition
['Infections' 'Flu' 'Cancer' 'Asthma' 'Heart Disease' 'Alzheimer’s'
 'Diabetes' 'Obesity']
--------------------------------------------------
Hospital
['Northwestern Memorial Hospital'
 'UI Health (University of Illinois Hospital)' 'UChicago Medicine'
 'Loyola University Medical Center']
--------------------------------------------------
Insurance Provider
['Blue Cross' 'UnitedHealthcare' 'Aetna' 'Cigna' 'Medicare']
--------------------------------------------------
Admission Type
['Emergency' 'Elective' 'Routine' 'Urgent']
--------------------------------------------------

# **Feature Engineering**

In [25]:
#Extracting the day, month and year from the Admission Date
data['Admission Day'] = data['Date of Admission'].dt.day_name()
data['Admission Month'] = data['Date of Admission'].dt.month
data['Admission Year'] = data['Date of Admission'].dt.year

In [26]:
print("Unique values in Admission Year")
print(data["Admission Year"].unique())

Unique values in Admission Year
[2024 2019 2022 2020 2023 2021]

In [27]:
print("Unique values in Admission Week Day")
print(data["Admission Day"].unique())

Unique values in Admission Week Day
['Wednesday' 'Tuesday' 'Thursday' 'Monday' 'Sunday' 'Friday' 'Saturday']

In [28]:
print("Unique values in Admission Month")
print(data["Admission Month"].unique())

Unique values in Admission Month
[ 1  8  9 11 12  7  5  4 10  6  3  2]

In [29]:
print("Frequency values in Admission Year", '\n')
print(data.groupby("Admission Year").size().sort_values(ascending=False))

Frequency values in Admission Year

Admission Year
2020    11285
2023    11026
2022    11017
2021    10931
2019     7387
2024     3854
dtype: int64

In [30]:
print("Frequency values in Admission Month", '\n')
print(data.groupby("Admission Month").size().sort_values(ascending=False))

Frequency values in Admission Month

Admission Month
8     4832
7     4812
6     4699
1     4692
10    4678
3     4672
12    4649
5     4599
11    4548
9     4546
4     4518
2     4255
dtype: int64

In [31]:
print("Frequency values in Admission Week Day", '\n')
print(data.groupby("Admission Day").size().sort_values(ascending=False))

Frequency values in Admission Week Day

Admission Day
Thursday     7989
Tuesday      7982
Wednesday    7950
Sunday       7920
Saturday     7901
Friday       7892
Monday       7866
dtype: int64

#**One-Hot Encoding**

In [32]:
#Converting Required Categorical Features to Numeric using One-Hot Encoding
Encoded_Data=pd.get_dummies(data, columns=["Gender","Blood Type","Medical Condition","Hospital","Insurance Provider","Admission Day"],drop_first=True,dtype=int)
Encoded_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 41 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Name                                                  55500 non-null  object
 1   Age                                                   55500 non-null  int64
 2   Date of Admission                                     55500 non-null  datetime64[ns]
 3   Doctor                                                55500 non-null  object
 4   Billing Amount                                        55500 non-null  float64
 5   Room Number                                           55500 non-null  int64
 6   Admission Type                                        55500 non-null  object
 7   Discharge Date                                        55500 non-null  datetime64[ns]
 8   Medication                                            55500 non-null  object
 9   Test Results                                          55500 non-null  object
 10  Length of Stay                                        55500 non-null  int64
 11  Admission Month                                       55500 non-null  int32
 12  Admission Year                                        55500 non-null  int32
 13  Gender_Male                                           55500 non-null  int64
 14  Blood Type_A-                                         55500 non-null  int64
 15  Blood Type_AB+                                        55500 non-null  int64
 16  Blood Type_AB-                                        55500 non-null  int64
 17  Blood Type_B+                                         55500 non-null  int64
 18  Blood Type_B-                                         55500 non-null  int64
 19  Blood Type_O+                                         55500 non-null  int64
 20  Blood Type_O-                                         55500 non-null  int64
 21  Medical Condition_Asthma                              55500 non-null  int64
 22  Medical Condition_Cancer                              55500 non-null  int64
 23  Medical Condition_Diabetes                            55500 non-null  int64
 24  Medical Condition_Flu                                 55500 non-null  int64
 25  Medical Condition_Heart Disease                       55500 non-null  int64
 26  Medical Condition_Infections                          55500 non-null  int64
 27  Medical Condition_Obesity                             55500 non-null  int64
 28  Hospital_Northwestern Memorial Hospital               55500 non-null  int64
 29  Hospital_UChicago Medicine                            55500 non-null  int64
 30  Hospital_UI Health (University of Illinois Hospital)  55500 non-null  int64
 31  Insurance Provider_Blue Cross                         55500 non-null  int64
 32  Insurance Provider_Cigna                              55500 non-null  int64
 33  Insurance Provider_Medicare                           55500 non-null  int64
 34  Insurance Provider_UnitedHealthcare                   55500 non-null  int64
 35  Admission Day_Monday                                  55500 non-null  int64
 36  Admission Day_Saturday                                55500 non-null  int64
 37  Admission Day_Sunday                                  55500 non-null  int64
 38  Admission Day_Thursday                                55500 non-null  int64
 39  Admission Day_Tuesday                                 55500 non-null  int64
 40  Admission Day_Wednesday                               55500 non-null  int64
dtypes: datetime64[ns](2), float64(1), int32(2), int64(31), object(5)
memory usage: 16.9+ MB

In [33]:
print(Encoded_Data.columns)

Index(['Name', 'Age', 'Date of Admission', 'Doctor', 'Billing Amount',
       'Room Number', 'Admission Type', 'Discharge Date', 'Medication',
       'Test Results', 'Length of Stay', 'Admission Month', 'Admission Year',
       'Gender_Male', 'Blood Type_A-', 'Blood Type_AB+', 'Blood Type_AB-',
       'Blood Type_B+', 'Blood Type_B-', 'Blood Type_O+', 'Blood Type_O-',
       'Medical Condition_Asthma', 'Medical Condition_Cancer',
       'Medical Condition_Diabetes', 'Medical Condition_Flu',
       'Medical Condition_Heart Disease', 'Medical Condition_Infections',
       'Medical Condition_Obesity', 'Hospital_Northwestern Memorial Hospital',
       'Hospital_UChicago Medicine',
       'Hospital_UI Health (University of Illinois Hospital)',
       'Insurance Provider_Blue Cross', 'Insurance Provider_Cigna',
       'Insurance Provider_Medicare', 'Insurance Provider_UnitedHealthcare',
       'Admission Day_Monday', 'Admission Day_Saturday',
       'Admission Day_Sunday', 'Admission Day_Thursday',
       'Admission Day_Tuesday', 'Admission Day_Wednesday'],
      dtype='object')

# **Label Encoding**

In [34]:
#Encoding the Target Feature by using Label Encoding i,e Mapping Function
Admission_Type_Mapping = {'Emergency': 0, 'Elective': 1, 'Urgent': 2,'Routine':3}
Encoded_Data['Admission Type'] = Encoded_Data['Admission Type'].map(Admission_Type_Mapping)

In [35]:
Encoded_Data['Admission Type'].value_counts()

Admission Type
0    20104
1    13280
2    11816
3    10300
Name: count, dtype: int64

In [36]:
Encoded_Data.sample(2)

,Name,Age,Date of Admission,Doctor,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,...,Insurance Provider_Blue Cross,Insurance Provider_Cigna,Insurance Provider_Medicare,Insurance Provider_UnitedHealthcare,Admission Day_Monday,Admission Day_Saturday,Admission Day_Sunday,Admission Day_Thursday,Admission Day_Tuesday,Admission Day_Wednesday
42315,Larry Williams,42,2023-04-07,Julie Allen,8024.465579,400,1,2023-04-12,Orlistat,Abnormal,...,0,1,0,0,0,0,0,0,0,0
35326,Kevin Palmer,78,2021-07-08,Jack Sanders,40186.223929,414,1,2021-08-08,Aspirin,Inconclusive,...,0,0,0,1,0,0,0,1,0,0

# **Model Selection**

In [37]:
from sklearn.model_selection import train_test_split   #Splitting the Data
from sklearn.linear_model import LogisticRegression    #Logistic Regression
from sklearn.tree import DecisionTreeClassifier        #Decision Tree
from sklearn.ensemble import RandomForestClassifier    #Random Forest Classification
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score  #Model Evaluation Parameters

In [38]:
#Splitting the Training and Target Features
x=Encoded_Data.drop(['Name','Date of Admission', 'Doctor','Billing Amount','Room Number','Admission Type','Discharge Date', 'Medication','Test Results', 'Length of Stay'], axis=1)
y=Encoded_Data['Admission Type']

In [39]:
print(x.shape,y.shape)

(55500, 31) (55500,)

In [40]:
#Training and Testing the Data
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=2)

In [41]:
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(44400, 31) (11100, 31) (44400,) (11100,)

In [49]:
Models={
    'Logistic Regression':LogisticRegression(max_iter=1000),
    'Decision Tree':DecisionTreeClassifier(),
    'Random Forest':RandomForestClassifier()}

# **Model Evaluation**

In [50]:
#Creating an Empty Result Set
Results = []

In [51]:
#Training and Evaluating the Each Model
for model_name, model in Models.items():
  model.fit(X_train, Y_train)
  Y_pred = model.predict(X_test)

  accuracy = accuracy_score(Y_test, Y_pred)
  precision = precision_score(Y_test, Y_pred, average='weighted',zero_division=0)
  recall = recall_score(Y_test, Y_pred, average='weighted',zero_division=0)
  f1 = f1_score(Y_test, Y_pred, average='weighted',zero_division=0)

  Results.append([model_name, accuracy,precision,recall,f1])

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [52]:
# Create a DataFrame to store results
Results_df = pd.DataFrame(Results, columns=['Model', 'Accuracy', 'Precision', 'Recall', 'F1-Score'])
Results_df

                 Model  Accuracy  Precision    Recall  F1-Score
0  Logistic Regression  0.457568   0.288060  0.457568  0.343931
1        Decision Tree  0.319279   0.323408  0.319279  0.321089
2        Random Forest  0.423964   0.383094  0.423964  0.389622